In [2]:
#mean removal
import numpy as np
from sklearn import preprocessing
data=np.array([[2],[4],[6],[8],[10]])

mean=data.mean(axis=0)

mean_removed=data-mean
print(mean_removed)
print(mean_removed.std(axis=0))
print(mean_removed.mean(axis=0))
data_standardize=preprocessing.scale(data)
print(data_standardize.std(axis=0))
print(data_standardize.mean(axis=0))

[[-4.]
 [-2.]
 [ 0.]
 [ 2.]
 [ 4.]]
[2.82842712]
[0.]
[1.]
[0.]


In [3]:
#scaling

import numpy as np
from sklearn import preprocessing
data=np.array([[10],[20],[30],[40],[50]])
print(data)
print('='*50)
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_data=data_scaler.fit_transform(data)
print(scaled_data)

[[10]
 [20]
 [30]
 [40]
 [50]]
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [4]:
#normalization
import numpy as np
from sklearn import preprocessing
data=np.array([[3,4],[1,2],[5,12]])
print(data)
print('='*50)

#l1
normalized_l1=preprocessing.normalize(data,norm='l1')
print(normalized_l1)
print('='*50)

#l2
normalized_l2=preprocessing.normalize(data,norm='l2')
print(normalized_l2)

[[ 3  4]
 [ 1  2]
 [ 5 12]]
[[0.42857143 0.57142857]
 [0.33333333 0.66666667]
 [0.29411765 0.70588235]]
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.38461538 0.92307692]]


In [6]:
#binarization
import numpy as np
from sklearn import preprocessing
data=np.array([[8.9],[9.9],[10.9],[9.2],[6.9],[7.2]])
print(data)
print('='*50)
binarized_data=preprocessing.Binarizer(threshold=8).transform(data)
print(binarized_data)

[[ 8.9]
 [ 9.9]
 [10.9]
 [ 9.2]
 [ 6.9]
 [ 7.2]]
[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]


In [7]:
#label encoding
from sklearn import preprocessing

labels=['mango','banana','apple','mango','orange','banana']
print(labels)

label_encoder=preprocessing.LabelEncoder()
op=label_encoder.fit_transform(labels)
print(op)

test_labels=['mango','banana']
print(test_labels)
print(label_encoder.transform(test_labels))
test_code=[2,1]
print(label_encoder.inverse_transform(test_code))

['mango', 'banana', 'apple', 'mango', 'orange', 'banana']
[2 1 0 2 3 1]
['mango', 'banana']
[2 1]
['mango' 'banana']


In [1]:
#desition tree
import numpy as np
from sklearn.tree import DecisionTreeRegressor

x=np.array([[1],[2],[3],[4],[5]])
y=np.array([[30000],[35000],[40000],[45000],[50000]])

model=DecisionTreeRegressor(max_depth=2)
model.fit(x,y)

print(model.predict([[6]]))

[47500.]


In [4]:
#support vector machine
import numpy as np
from sklearn.svm import SVR

x=np.array([[1],[2],[3],[4],[5]])
y=np.array([[30000],[35000],[40000],[45000],[50000]])

model=SVR(kernel='rbf',C=1000,epsilon=500)

model.fit(x,y)
print(model.predict([[6]]))

[40741.52675367]


C:\Users\atmiya\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data={
    'Marks':[25,35,40,55,68,75,85],
    'Result':['Fail','Fail','Pass','Pass','Pass','Pass','Pass']
}
df=pd.DataFrame(data)

df['Result']=df['Result'].map({'Fail':0,'Pass':1})
x=df[['Marks']]
y=df['Result']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

new_marks=np.array([[30],[48],[39]])
prediction=model.predict(new_marks)
for m,p in zip(new_marks,prediction):
    print(f"Marks:{m[0]}->{'Pass' if p==1 else 'Fail'}")


Marks:30->Fail
Marks:48->Pass
Marks:39->Fail


C:\Users\atmiya\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [9]:
#native bayes classifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

data = {
    'Message': [
        "win lottery now",
        "lowest price offer",
        "how are you?",
        "lets meet tomorrow",
        "congratulations,you won a lottery",
        "reminder for the meeting"
    ],
    'Label': ['Spam', 'Spam', 'Not Spam', 'Not Spam', 'Spam', 'Not Spam']
}

df = pd.DataFrame(data)
df['Label'] = df['Label'].map({'Not Spam': 0, 'Spam': 1})

x = df['Message']
y = df['Label']

vectorizer = CountVectorizer()
x_feature = vectorizer.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x_feature, y, test_size=0.3, random_state=1)

model = MultinomialNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

new_emails = ["free offer lottery just for you", "hi, are we still lowest price for lottery today?"]
new_feature = vectorizer.transform(new_emails)
predictions = model.predict(new_feature)

for email, p in zip(new_emails, predictions):
    print(f"Email: '{email}' -> {'Spam' if p == 1 else 'Not Spam'}")



Email: 'free offer lottery just for you' -> Spam
Email: 'hi, are we still lowest price for lottery today?' -> Spam


In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

data = {
    'Message': [
        "win lottery now",
        "lowest price offer",
        "how are you?",
        "lets meet tomorrow",
        "congratulations,you won a lottery",
        "reminder for the meeting"
    ],
    'Label': ['Spam', 'Spam', 'Not Spam', 'Not Spam', 'Spam', 'Not Spam']
}

df = pd.DataFrame(data)
df['Label'] = df['Label'].map({'Not Spam': 0, 'Spam': 1})

x = df['Message']
y = df['Label']

vectorizer = CountVectorizer()
x_feature = vectorizer.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x_feature, y, test_size=0.3, random_state=1)

model = MultinomialNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

new_emails = ["free offer lottery just for you", "hi, are we still lowest price for lottery today?"]
new_feature = vectorizer.transform(new_emails)
predictions = model.predict(new_feature)

for email, p in zip(new_emails, predictions):
    print(f"Email: '{email}' -> {'Spam' if p == 1 else 'Not Spam'}")


Email: 'free offer lottery just for you' -> Spam
Email: 'hi, are we still lowest price for lottery today?' -> Spam
